version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3312:3312'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./dockR:/dockR"
      - "/material:/dockR/material"
      - "/material:/dockR/material.frontend"

    ports:
      - "8000:8000"
    depends_on:
      - db
