# Generated by Django 3.0 on 2019-12-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='title',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addpost',
            name='data',
            field=models.CharField(max_length=200),
        ),
    ]
