# Generated by Django 2.2 on 2020-03-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='title',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='author',
            new_name='name',
        ),
    ]
